config/routes.rb
Rails.application.routes.draw do

  root to:'homes#top'
  get  'home/about' =>'homes#about' ,as: 'homes_about'
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :index, :update]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   
   validates :title, presence: true
   validates :body, presence: true,length: {maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  
  has_many :books, dependent: :destroy
  
  validates :name, presence: true,  length: { minimum: 2, maximum: 20},uniqueness: true
  validates :introduction,length: {maximum: 50}
  
def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
 before_action :authenticate_user!
 
 def show
  @book = Book.find(params[:id])
  @book_new = Book.new
  @books= Book.all
 end
 
 def index
  @book=Book.new
  @books=Book.all
  
 end
 
 def create
   @book=Book.new(book_params)
   @book.user_id = current_user.id
  if @book.save
   redirect_to book_path(@book), notice:'You have created book successfully.'
  else
   @books=Book.all
   render :index
  end
 end
 
 
 def edit
  @book=Book.find(params[:id])
  if @book.user != current_user
   redirect_to books_path
  end
 end
 
 def update
   @book=Book.find(params[:id])
   if @book.update(book_params)
     redirect_to book_path(@book.id), notice:'You have updated book successfully'
   else
     render :edit
   end
 end
 
 def destroy
  book=Book.find(params[:id])
  book.destroy
  redirect_to books_path
 end
 
 private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
before_action :authenticate_user!
before_action :user_check,only:[:edit, :update]


  def show
    @user=User.find(params[:id])
    @book=Book.new
    @books=Book.where(user_id: @user.id)
  end
  
  def index
    @book=Book.new
    @books=Book.all
    @user=current_user
    @users=User.all
  end
  
  def edit
   @user=User.find(params[:id])
  end
  
  def update
    @user=User.find(params[:id])
   if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
   else
    render :edit
   end
  end
  
  def user_check
   @user=User.find(params[:id])
   unless @user==current_user
    redirect_to user_path(current_user.id)
   end
  end
  
   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>
  
  <h4>本文</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Update Book' %>
  
<% end %>

<%= link_to"Show",book_path(params[:id]) %>
<%= link_to"Back",books_path %>

app/views/books/index.html.erb
<div class = "container">

<div class = "row">

<div class = "col-md-3">

<%= render 'users/info', book: @book, user: current_user %>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

</div>

<div class = "col-md-8 offset-md-1">

<h1>Books</h1>
<table>
 <thead>
  <tr>
   <th></th>
   <th>Title</th>
   <th>pinion</th>
   <th colspan="3"></th>
  </tr>
  </thead>
  
  <tbody>
  <% @books.each do |book| %>
  <div>
   <tr>
    <td><%= link_to user_path(book.user.id) do %>
      <%= image_tag book.user.get_profile_image(100,100) %>
      <% end %>
     </td>
    <td><%= link_to book_path(book.id) do %>
    <%= book.title %>
    <% end %></td>
    <td><%= book.body %></td>
   </tr>
  </div>
  <% end %>
  </tbody>
  </table>
  
  </div>
  </div>

app/views/books/show.html.erb
<div class = "container">

<div class = "row">

<div class = "col-md-3">

<%= render 'users/info', book: @book_new, user: @book.user %>

</div>

<div class = "col-md-8 offset-md-1"

<hi>Book detail</hi>
<table>
 <tbody>
  <tr>
     <td>
      <%= link_to user_path(@book.user.id) do %>
       <%= image_tag @book.user.get_profile_image(200,200) %>
       <%= @book.user.name %>
      <% end %>
     </td>
    
    <td><%= link_to @book.title,book_path(@book.id) %></td>
    <td><%= @book.body %></td>
    
    <% if @book.user == current_user %>
    <td><%= link_to"Edit",edit_book_path(@book.id) %></td>
    <td><%= link_to"Destroy",book_path(@book.id),method: :delete %></td>
  </tr>
    <% end %>
  </tbody>
    
</table>

</div>
</div>

app/views/homes/about.html.erb
<h>Welcome to <i class="fas fa-book"></i>Bookers!</h>

app/views/homes/top.html.erb
<div class = container>
<div class = row>
<div class = col-md-9>

<p><%=notice%></p>

<h1>Welcome to <i class="fas fa-book"></i>Bookers</h1>
<p>In Bookers,</p>
<p>you can share exchange your opinions,inpressions,and emotions</p>
<p>about various books!</p>


<%= link_to "Log in",new_user_session_path, class: "btn btn-outline-secondary btn-block"  %>


<%= link_to "Sign up" ,new_user_registration_path, class: "btn btn-outline-secondary btn-block"  %>

</div>
</div>
</div>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
 <html>
   <head>
     <title>Bookers2</title>
     <meta name="viewport" content="width=device-width,initial-scale=1">
     <%= csrf_meta_tags %>
     <%= csp_meta_tag %>
 
     <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     
     <script src="https://kit.fontawesome.com/7f7a7e072f.js" crossorigin="anonymous"></script>
   </head>

  <body>
    
        
    <header>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
    
        
     <li class="navbar-brand ">
      <%= link_to "Bookers",root_path,class:"text-light" %>
     </li>
    
    <div class = "collapse navbar-collapse">
    
        <ul class="navbar-nav ml-auto">
    
            <% if user_signed_in? %>
             <li class="nav-item">
               <%= link_to  user_path(current_user),class:"nav-link text-light" do %>
                <i class="fas fa-home"></i>Home
               <% end %>
             </li>
             
             <li class="nav-item">
                <%= link_to  users_path,class:"nav-link text-light" do %>
                 <i class="fas fa-users"></i>Users
                <% end %>
              </li>
              
              <li class="nav-item">
                <%= link_to  books_path,class:"nav-link text-light" do %>
                 <i class="fas fa-book-open"></i>Books
                <% end %>
              </li>
              
             <li class="nav-item">
                <%= link_to  destroy_user_session_path, method: :delete,class:"nav-link text-light"  do %>
                 <i class="fas fa-sign-out-alt"></i>Log out
                <% end %>
             </li>
              
            <% else %>
             <li class="nav-item">
              <%= link_to  root_path,class:"nav-link text-light" do %>
               <i class="fas fa-home"></i>Home
              <% end %>
             </li>
             
             <li class="nav-item">
              <%= link_to  homes_about_path,class:"nav-link text-light" do %>
               <i class="fas fa-link"></i>About
              <% end %>
             </li>
            
             <li class="nav-item">
                <%= link_to  new_user_registration_path,class:"nav-link text-light" do %>
                 <i class="fas fa-user-plus"></i>Sign up
                <% end %>
              </li>
              
             <li class="nav-item">
                <%= link_to  user_session_path, method: :post,class:"nav-link text-light"  do%>
                 <i class="fas fa-sign-in-alt"></i>Log in
                <% end %>
             </li>
              
            <% end %>
        </ul>
    
    </div>
    
     
    </nav>
   
    </header>
    
    <%= yield %>
    
  <footer>
    <P>CopyRight Infratop.inc</P>
  </footer>

  
    
  </body>
  
  
  
  
</html>

app/views/users/_info.html.erb
<div class = container>
<div class = row>
<div class = col-md-4>

<p><%=notice%></p>

<h1>User info</h1>
<%= image_tag user.get_profile_image(200,200) %>

<table>
 <tbody>
  <tr>
   <th>name</th>
   <th><%= user.name %></th>
  </tr>
  <tr>
   <th>introduction</th>
   <th><%= user.introduction %></th>
  </tr>
 </tbody>
</table>

<%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog"></i>
<% end %>

<h1>New book</h1>


<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%=form_with model: book do|f| %>
 <h3>Title</h3>
 <%=f.text_field :title %>
 
 <h4>Opinion</h4>
 <%=f.text_area :body %>
 
 <%=f.submit'Create Books'%>
<% end %>
  
</table>

</div>
</div
</div>
</div>

app/views/users/edit.html.erb
<h1>Users info</h1>

<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>

  <h2>Name</h2>
  <%= f.text_field :name %>
  
  <h2>Image</h2>
  <%= f.file_field :profile_image,  accept: "image/*", placeholder: "ファイルを選択" %>  
  
  <h2>Introduction</h2>
  <%= f.text_area :introduction %>
  
  <%= f.submit 'Update User' %>
  
<% end %>

app/views/users/index.html.erb
<div class = "container">

<div class = "row">

<div class = "col-md-3">

<%= render 'users/info', book: @book, user: current_user %>

</div>

<div class = "col-md-8 offset-md-1">

<h1>Users</h1>
<table>
 <thead>
  <tr>
   <th>image</th>
   <th>name</th>
   <th colspan="3"></th>
  </tr>
 </thead>
 
 <tbody>
  <% @users.each do |user| %>
  <tr>
  <td><%= image_tag user.get_profile_image(100,100) %></td>
  <td><%= user.name %></td>
  <td><%= link_to"Show",user_path(user.id) %></td>
  </tr>
  <% end %>
 </tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class = "container">

<div class = "row">

<div class = "col-md-3">
 
<%= render 'users/info', book: @book, user: @user %>

</div>

<div class = "col-md-8 offset-md-1" >

<h1>Books</h1>

<table>
 <thead>
  <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  </tr>
 </thead>
 
 <tbody>
  <% @books.each do |book| %>
  <tr>
    <td></td>
    <td><%= link_to user_path(@user) do %>
     <%= image_tag @user.get_profile_image(100,100) %>
     <% end %>
     </td>
    <td><%= link_to book.title,book_path(book.id) %></td>
    <td><%= book.body %></td>
  </tr>
  <% end %>
 </tbody>

</table>

</div>
</div>